[package]
name = 'aptogotchi'
version = '1.0.0'
upgrade_policy = "compatible"

[addresses]
aptogotchi = '_'

[dev-addresses]
aptogotchi = "0x100"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-token-objects'
